services:
  bytebank-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
    restart: always 